apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 840903411766.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 840903411766.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 26e712e9
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
